# vim: set ft=ruby

cask_args appdir: '/Applications'

brew 'awscli'
brew 'coreutils'
brew 'docker'
brew 'docker-compose'
brew 'docker-machine'
brew 'git'
brew 'gnupg'
brew 'heroku'
brew 'htop'
brew 'irssi'
brew 'keybase'
brew 'moreutils'
brew 'mplayer'
brew 'newsbeuter'
brew 'nmap'
brew 'node'
brew 'pass'
brew 'postgresql'
brew 'python3'
brew 'rbenv'
brew 'redis'
brew 'ruby'
brew 'ruby-build'
brew 's3cmd'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'zsh'

tap 'homebrew/science'

tap 'caskroom/cask'

cask 'atom'
cask 'bitbar'
cask 'cyberduck'
cask 'droplr'
cask 'google-chrome'
cask 'minecraft'
cask 'paintbrush'
cask 'slack'
cask 'spectacle'
cask 'torbrowser'
cask 'transmission'
cask 'vlc'
cask 'dropbox'
