#!/bin/bash

set -e

ROOT=$PWD

link_files () {
  if [[ ! -z "$FORCE" ]]; then
    echo "removing $2 if it exists"
    rm -rf $2
  fi
  ln -vs `pwd`/$1 $2
  echo "Linked $1 to $2"
}

install_dotfiles () {
  echo 'installing dotfiles'

  for source in `find src/ -maxdepth 2 -mindepth 1`
  do

    dest="$HOME/.$(basename $source)"

    if [ ! -e $dest ]
    then
      link_files $source $dest
    else
      echo "$source already exists! Skipping $dest"
    fi

  done
}

install_dotfiles
