#!/bin/bash

set -euo pipefail

ROOT=$PWD

# overwrite existing files? *DANGER*
: ${FORCE:=false}

link_files () {
  rm -rf $2
  ln -vs `pwd`/$1 $2
  echo "Linked $1 to $2"
}

install_dotfiles () {
  echo 'installing dotfiles'

  for source in `find src/ -maxdepth 2 -mindepth 1`; do

    dest="${HOME}/.$(basename ${source})"
    
    if [ ${FORCE} == true ]; then
      rm -rf ${dest}
    fi

    if [ ! -e ${dest} ]; then
      link_files ${source} ${dest}
    else
      echo "${source} already exists! Skipping ${dest}"
    fi

  done
}

install_dotfiles

echo "linking local to ~/.local"
echo `ln -sv local ~/.local`
