#!/bin/bash

set -euo pipefail

ROOT=$PWD

# overwrite existing files? *DANGER*
: ${FORCE:=false}

link_files () {
  rm -rf $2
  ln -s `pwd`/$1 $2
  red='\033[0;32m'
  nc='\033[0m'
  echo -e "${red}---> linked $1 to $2${nc}"
}

install_dotfiles () {
  for source in `find src/ -maxdepth 2 -mindepth 1`; do

    dest="${HOME}/.${source#src//}"
    if [ ${FORCE} == true ]; then
      rm -rf ${dest}
    fi

    if [ ! -e ${dest} ]; then
      link_files ${source} ${dest}
    else
      echo "---> skipping ${dest}"
    fi

  done
}

install_dotfiles
