#!/bin/bash

# nothing to see here
. ~/.aliases
. ~/.secrets

export LSCOLORS="exfxcxdxbxegedabagacad"
alias ls="ls -lGH"

# mcfly
if [[ -r "$(brew --prefix)/opt/mcfly/mcfly.bash" ]]; then
  source "$(brew --prefix)/opt/mcfly/mcfly.bash"
fi
export PATH="/usr/local/opt/ruby/bin:$PATH"

EMOJI=(

💦
💧
💨
💙
💎
🌈
🌀
❄️
🐳
🚎
🗻
✈️
💠
)

# https://direnv.net
eval "$(direnv hook bash)"

# Git branch in prompt.
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

directory() {
  echo $(basename $(dirname "$PWD"))/$(basename "$PWD")
}

emoji="${EMOJI[$RANDOM % ${#EMOJI[@]}]}"

function prompt {
  local directory_color="\[\033[38;5;213m\]"
  local branch_color="\[\033[38;5;200m\]"
  local RESETCOLOR="\[\e[00m\]"

  export PS1="$directory_color[\W]$RESETCOLOR$branch_color\$(parse_git_branch) ${emoji} $RESETCOLOR"
}
prompt

export EDITOR=vim

# i do not care that u deprecated something
export PYENV_VIRTUALENV_DISABLE_PROMPT=0

# various environment managers
if [ -e /usr/local/bin/pyenv ]; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

if [ -e /usr/local/bin/rbenv ]; then
  eval "$(rbenv init -)"
fi

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
