#!/bin/bash

. ~/.aliases

# nothing to see here
. ~/.secrets

export LSCOLORS="exfxcxdxbxegedabagacad"
alias ls="ls -lGH"

# mcfly
if [[ -r "$(brew --prefix)/opt/mcfly/mcfly.bash" ]]; then
  source "$(brew --prefix)/opt/mcfly/mcfly.bash"
fi
export PATH="/usr/local/opt/ruby/bin:$PATH"

# don't update homebrew as often
HOMEBREW_AUTO_UPDATE_SECS=3600

EMOJI=(
💦
💧
💨
💙
💎
🌈
🌀
🐳
🚎
🗻
✈️
💠
)

# https://direnv.net
if [[ -e "/usr/local/bin/direnv" ]]
then
  eval "$(direnv hook bash)"
fi

# Git branch in prompt.
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

directory() {
  echo $(basename $(dirname "$PWD"))/$(basename "$PWD")
}

emoji="${EMOJI[$RANDOM % ${#EMOJI[@]}]}"
emoji=':'

function prompt {
  local directory_color="\[\033[38;5;13m\]"
  local branch_color="\[\033[38;5;9m\]"
  local black="\[\033[38;5;16m\]"
  local RESETCOLOR="\[\e[00m\]"

  export PS1="$directory_color[\W]${RESETCOLOR}$branch_color\$(parse_git_branch) ${emoji} ${RESETCOLOR}"
}
prompt

export EDITOR=vim

# i do not care that u deprecated something
export PYENV_VIRTUALENV_DISABLE_PROMPT=0

# various environment managers
if [ -e /usr/local/bin/pyenv ]; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

export PATH="/usr/local/opt/ruby/bin:$PATH"
if [ -e /usr/local/bin/rbenv ]; then
  eval "$(rbenv init -)"
fi

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"

export PATH="$HOME/.poetry/bin:$PATH"
