#!/usr/bin/env Rscript

options(repos=c("http://cran.us.r-project.org"))

options(prompt="R> ")

# autocomplete in require()
# https://twitter.com/JennyBryan/status/631012796235276288
utils::rc.settings(ipck=TRUE)

if (interactive()) {

  # zap() removes all variables in current session
  # from http://r.789695.n4.nabble.com/How-to-Clear-all-variables-stored-in-current-and-previous-sessions-td873058.html
  zap <- function() rm(list=ls(all=TRUE))
  cat("\014")
}
