#!/usr/bin/env Rscript

# vim: ft=R

# hosted on Amazon
options(repos = c(CRAN = "https://cran.rstudio.com"))


# rice
options(
  rice.color_scheme = "native",
  rice.editing_mode = "vi",
  rice.complete_while_typing = FALSE
)

if(interactive()) {
  options(editor="vim")
  options(prompt="r> ")
  options(width=80)
  options(stringsAsFactors=FALSE)
}
